/**
 * API: POST /api/classes/ensure  { studentId, date: 'YYYY-MM-DD' }
 *
 * Make sure a student has a class on a scheduled day so attendance can be
 * marked on it — used for days before their schedule existed. Returns the
 * existing class covering them that day, or creates their own class at their
 * scheduled time. Teacher / admin only.
 */

import { NextRequest } from 'next/server';
import { requireAuth, authErrorResponse } from '@/lib/auth/middleware';
import { getDoc, queryDocs, setDoc, nowISO } from '@/lib/firebase/firestore';
import { COLLECTIONS } from '@/domain/constants';
import { classStudentIds } from '@/lib/classes/dedupe';
import { parseSchedule, startFor, addMinutesHHMM } from '@/lib/classes/student-schedule';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

const Schema = z.object({
  studentId: z.string().min(1),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
});

export async function POST(request: NextRequest) {
  try {
    const auth = await requireAuth(request, ['teacher', 'super_admin']);
    const parsed = Schema.safeParse(await request.json().catch(() => ({})));
    if (!parsed.success) return Response.json({ error: 'Invalid request' }, { status: 400 });
    const { studentId, date } = parsed.data;

    const profile = await getDoc<Record<string, unknown>>(COLLECTIONS.STUDENT_PROFILES, studentId);
    if (!profile) return Response.json({ error: 'Student not found' }, { status: 404 });

    // Already has their own / group / extra class that day?
    const sameDay = await queryDocs<Record<string, unknown> & { id: string }>(COLLECTIONS.CLASS_INSTANCES, [
      { type: 'where', field: 'scheduledStartTime', op: '>=', value: `${date}T00:00:00+05:30` },
      { type: 'where', field: 'scheduledStartTime', op: '<=', value: `${date}T23:59:59+05:30` },
    ]);
    const existing = sameDay.find(
      (i) => classStudentIds(i).includes(studentId) && !String(i.status ?? '').includes('cancel'),
    );
    if (existing) return Response.json({ success: true, instanceId: existing.id, created: false });

    const sched = parseSchedule(profile.classSchedule);
    const dow = new Date(`${date}T00:00:00Z`).getUTCDay();
    const time = (sched && startFor(sched, dow)) ?? '05:30';
    const minutes = sched?.durationMinutes ?? 60;
    const instanceId = `${studentId}_${date}`;

    await setDoc(COLLECTIONS.CLASS_INSTANCES, instanceId, {
      slotId: 'student-schedule',
      teacherId: auth.uid,
      batchBandId: (profile.currentBatchBandId as string) ?? '',
      studentIds: [studentId],
      kind: 'regular',
      scheduledStartTime: `${date}T${time}:00+05:30`,
      scheduledEndTime: `${date}T${addMinutesHHMM(time, minutes)}:00+05:30`,
      timezone: 'Asia/Kolkata',
      status: 'scheduled',
      cancellationReason: null,
      rescheduleTargetInstanceId: null,
      googleMeetLink: null,
      meetLink: null,
      googleCalendarEventId: null,
      lessonPlanItemId: null,
      teachingUnitId: null,
      notifiedCancellation: false,
      autoGenerated: false,
      createdBy: auth.uid,
      createdAt: nowISO(),
    });

    return Response.json({ success: true, instanceId, created: true });
  } catch (error) {
    return authErrorResponse(error);
  }
}
