/**
 * API: POST /api/classes/extra
 *
 * Add an extra class for one student, or a group class for several students
 * sharing one link. Optionally it replaces those students' regular class that
 * day (their own class is cancelled unless attendance was already marked).
 * Teacher / admin only.
 */

import { NextRequest } from 'next/server';
import { requireAuth, authErrorResponse } from '@/lib/auth/middleware';
import { createDoc, getDoc, queryDocs, updateDoc, nowISO } from '@/lib/firebase/firestore';
import { COLLECTIONS } from '@/domain/constants';
import { writeAuditLog, extractRequestMeta } from '@/services/audit/log';
import { addMinutesHHMM } from '@/lib/classes/student-schedule';
import { classStudentIds } from '@/lib/classes/dedupe';
import { normaliseMeetLink } from '@/lib/classes/links';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

const Schema = z.object({
  studentIds: z.array(z.string().min(1)).min(1).max(20),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  startTime: z.string().regex(/^\d{2}:\d{2}$/),
  durationMinutes: z.number().int().min(5).max(300),
  meetLink: z.string().max(300).optional(),
  replacesRegular: z.boolean().optional(),
  note: z.string().max(200).optional(),
});

export async function POST(request: NextRequest) {
  try {
    const auth = await requireAuth(request, ['teacher', 'super_admin']);
    const parsed = Schema.safeParse(await request.json().catch(() => ({})));
    if (!parsed.success) {
      return Response.json({ error: 'Invalid class details', details: parsed.error.flatten() }, { status: 400 });
    }
    const { date, startTime, durationMinutes, replacesRegular, note } = parsed.data;
    const studentIds = [...new Set(parsed.data.studentIds)];

    const profiles = await Promise.all(studentIds.map((id) => getDoc<Record<string, unknown>>(COLLECTIONS.STUDENT_PROFILES, id)));
    if (profiles.some((p) => !p)) {
      return Response.json({ error: 'Student not found' }, { status: 404 });
    }

    const link = parsed.data.meetLink ? normaliseMeetLink(parsed.data.meetLink) : '';
    const start = `${date}T${startTime}:00+05:30`;
    const end = `${date}T${addMinutesHHMM(startTime, durationMinutes)}:00+05:30`;

    const instanceId = await createDoc(COLLECTIONS.CLASS_INSTANCES, {
      slotId: 'extra',
      teacherId: auth.uid,
      batchBandId: (profiles[0]!.currentBatchBandId as string) ?? '',
      studentIds,
      kind: 'extra',
      scheduledStartTime: start,
      scheduledEndTime: end,
      timezone: 'Asia/Kolkata',
      status: 'scheduled',
      cancellationReason: null,
      rescheduleTargetInstanceId: null,
      customMeetLink: link || null,
      googleMeetLink: null,
      meetLink: null,
      googleCalendarEventId: null,
      lessonPlanItemId: null,
      teachingUnitId: null,
      notifiedCancellation: false,
      note: note?.trim() || null,
      autoGenerated: false,
      updatedAt: nowISO(),
    });

    // Replace each student's own regular class that day (if nothing recorded on it)
    let replaced = 0;
    if (replacesRegular) {
      const sameDay = await queryDocs<Record<string, unknown> & { id: string }>(COLLECTIONS.CLASS_INSTANCES, [
        { type: 'where', field: 'scheduledStartTime', op: '>=', value: `${date}T00:00:00+05:30` },
        { type: 'where', field: 'scheduledStartTime', op: '<=', value: `${date}T23:59:59+05:30` },
      ]);
      for (const inst of sameDay) {
        if (inst.id === instanceId || inst.kind === 'extra' || String(inst.status ?? '').includes('cancel')) continue;
        const ids = classStudentIds(inst);
        if (ids.length !== 1 || !studentIds.includes(ids[0])) continue;
        const recs = await queryDocs(COLLECTIONS.ATTENDANCE_RECORDS, [
          { type: 'where', field: 'classInstanceId', op: '==', value: inst.id },
        ]);
        if (recs.length) continue;
        await updateDoc(COLLECTIONS.CLASS_INSTANCES, inst.id, {
          status: 'cancelled',
          cancellationReason: 'replaced_by_group_or_extra',
          replacedBy: instanceId,
          updatedAt: nowISO(),
        });
        replaced++;
      }
    }

    const { ipAddress, userAgent } = extractRequestMeta(request);
    await writeAuditLog({
      actorId: auth.uid,
      actorRole: auth.role,
      action: 'CLASS_INSTANCE_CREATED',
      entityType: 'class_instance',
      entityId: instanceId,
      newState: { kind: 'extra', studentIds, start, end, replaced },
      ipAddress,
      userAgent,
    });

    return Response.json({ success: true, instanceId, replaced });
  } catch (error) {
    return authErrorResponse(error);
  }
}
