/**
 * lib/calendar/google.ts
 *
 * Google Calendar API wrapper for creating events with Google Meet links.
 * SERVER-ONLY.
 *
 * Meet links are generated by creating a Calendar event with conferenceData.
 * This requires the teacher to have completed OAuth and granted
 * the calendar.events scope.
 *
 * Environment variables required:
 *   GOOGLE_CALENDAR_CLIENT_ID
 *   GOOGLE_CALENDAR_CLIENT_SECRET
 *
 * IMPORTANT: This is a real integration — not a mock. It requires:
 *   1. Google Cloud project with Calendar API enabled
 *   2. OAuth consent screen configured
 *   3. Teacher completing the OAuth flow
 *   4. Refresh token stored server-side
 */

const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';
const GOOGLE_CALENDAR_API = 'https://www.googleapis.com/calendar/v3';

interface CalendarEventInput {
  summary: string;
  description: string;
  startTimeISO: string;  // UTC ISO string
  endTimeISO: string;
  timezone: string;       // IANA timezone
  idempotencyKey: string; // Used as conferenceData requestId
}

interface CalendarEventResult {
  eventId: string;
  meetLink: string | null;
}

/**
 * Refresh an OAuth access token using a stored refresh token.
 */
export async function refreshAccessToken(refreshToken: string): Promise<string> {
  const clientId = process.env.GOOGLE_CALENDAR_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CALENDAR_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error(
      'Google Calendar OAuth credentials not configured. ' +
      'Set GOOGLE_CALENDAR_CLIENT_ID and GOOGLE_CALENDAR_CLIENT_SECRET.'
    );
  }

  const response = await fetch(GOOGLE_TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: clientId,
      client_secret: clientSecret,
      refresh_token: refreshToken,
      grant_type: 'refresh_token',
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Google OAuth token refresh failed: ${response.status} ${errorBody}`);
  }

  const data = await response.json();
  return data.access_token;
}

/**
 * Create a Google Calendar event with a Google Meet conference link.
 *
 * @param accessToken - Valid OAuth access token for the teacher's Google account
 * @param input - Event details
 * @returns The Calendar event ID and the generated Meet link
 */
export async function createCalendarEventWithMeet(
  accessToken: string,
  input: CalendarEventInput
): Promise<CalendarEventResult> {
  const response = await fetch(
    `${GOOGLE_CALENDAR_API}/calendars/primary/events?conferenceDataVersion=1`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${accessToken}`,
      },
      body: JSON.stringify({
        summary: input.summary,
        description: input.description,
        start: {
          dateTime: input.startTimeISO,
          timeZone: input.timezone,
        },
        end: {
          dateTime: input.endTimeISO,
          timeZone: input.timezone,
        },
        conferenceData: {
          createRequest: {
            requestId: input.idempotencyKey,
            conferenceSolutionKey: {
              type: 'hangoutsMeet',
            },
          },
        },
      }),
    }
  );

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Google Calendar API error: ${response.status} ${errorBody}`);
  }

  const event = await response.json();

  // Extract Meet link from conference data entry points
  const meetLink = event.conferenceData?.entryPoints?.find(
    (ep: { entryPointType: string; uri: string }) => ep.entryPointType === 'video'
  )?.uri ?? null;

  return {
    eventId: event.id,
    meetLink,
  };
}

/**
 * Cancel (delete) a Google Calendar event.
 */
export async function cancelCalendarEvent(
  accessToken: string,
  eventId: string
): Promise<void> {
  const response = await fetch(
    `${GOOGLE_CALENDAR_API}/calendars/primary/events/${eventId}`,
    {
      method: 'DELETE',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
      },
    }
  );

  // 204 No Content = success, 410 Gone = already deleted (both fine)
  if (!response.ok && response.status !== 410) {
    const errorBody = await response.text();
    throw new Error(`Google Calendar delete error: ${response.status} ${errorBody}`);
  }
}

/**
 * Build the OAuth authorization URL for a teacher to connect their Google Calendar.
 *
 * @param redirectUri - The callback URL after OAuth (e.g., /api/auth/google-calendar/callback)
 * @param state - CSRF-safe state parameter
 */
export function buildGoogleOAuthUrl(redirectUri: string, state: string): string {
  const clientId = process.env.GOOGLE_CALENDAR_CLIENT_ID;

  if (!clientId) {
    throw new Error('GOOGLE_CALENDAR_CLIENT_ID is not configured.');
  }

  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: 'https://www.googleapis.com/auth/calendar.events',
    access_type: 'offline',
    prompt: 'consent',
    state,
  });

  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}

/**
 * Exchange an authorization code for tokens.
 */
export async function exchangeCodeForTokens(
  code: string,
  redirectUri: string
): Promise<{ accessToken: string; refreshToken: string }> {
  const clientId = process.env.GOOGLE_CALENDAR_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CALENDAR_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error('Google Calendar OAuth credentials not configured.');
  }

  const response = await fetch(GOOGLE_TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: clientId,
      client_secret: clientSecret,
      code,
      redirect_uri: redirectUri,
      grant_type: 'authorization_code',
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Google OAuth code exchange failed: ${response.status} ${errorBody}`);
  }

  const data = await response.json();
  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
  };
}
